stages:
   - build

Build: 
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ./ --dockerfile Dockerfile
      --destination $CI_REGISTRY_IMAGE:latest
      --verbosity=info
  rules:
    - if: $CI_COMMIT_TAG
