- name: Add octoprint group
  ansible.builtin.group:
    name: octoprint
    state: present

- name: Add octoprint user
  ansible.builtin.user:
    name: octoprint
    create_home: true
    shell: /bin/bash
    groups: octoprint,docker

- name: Prepare docker-compose.yml
  copy:
    content: |
            version: '3.8'
            services:
              octoprint:
                image: octoprint/octoprint
                restart: unless-stopped
                ports:
                  - 80:80
                devices:
                  - /dev/ttyUSB0:/dev/ttyUSB0
                volumes:
                - ./data:/octoprint
    dest: /home/octoprint/docker-compose.yml
    owner: octoprint
    group: octoprint
    mode: '0644'

- name: Start octoprint
  shell: docker compose -f /home/octoprint/docker-compose.yml up -d
